export const path = {
    HOME: '/*',
    LOGIN: 'dang-nhap',
    REGISTER: 'dang-ky',
    REGISTER_HOST: 'dang-ky-chu-tro',
    ROOM: 'phong-tro',
    BLOG: 'blog',
    BOOKING_LIST: 'danh-sach-dat-phong',
    VERIFY_EMAIL: 'verify-email',
    PROFILE: 'thong-tin-ca-nhan',
    CHANGE_PASSWORD: 'doi-mat-khau',
    RESET_PASSWORD: 'reset-password/:token',
    ROOM_DETAIL: 'chi-tiet/:tenPhong/:id',
    BLOG_DETAIL: 'chi-tiet-blog/:id',
    PAYMENT_RESULT: 'payment-result',
    HISTORY: 'lich-su-dat-phong',
    HISTORY_DETAIL: 'chi-tiet-lich-su/:id',

    //quản lý
    ADMIN: '/quan-ly',
    APPROVE_HOST: 'duyet-dang-ky-chu-tro',
    APPROVE_HOST_DETAIL: 'chi-tiet-dang-ky-chu-tro/:id',
    USER_MANAGER: 'quan-ly-tai-khoan',
    USER_LOCKED_MANAGER: 'quan-ly-tai-khoan-da-khoa',
    USER_DETAIL: 'chi-tiet-tai-khoan/:id',
    EDIT_USER: 'sua-tai-khoan',
    ADMIN_PROFILE: 'thong-tin-ca-nhan',
    APPROVE_POST: 'duyet-bai-dang',
    POST_ALL: 'danh-sach-cac-bai-dang',
    POST_DETAIL: 'chi-tiet-bai-dang/:id',
    BLOG_ALL: 'quan-ly-bai-viet',
    BLOG_ALL_DELETED: 'quan-ly-bai-viet-da-xoa',
    BLOG_MANAGER_DETAIL: 'chi-tiet-bai-viet/:id',
    ADD_BLOG: 'them-bai-viet',
    EDIT_BLOG: 'sua-bai-viet/:id',
    GENERAL_STATISTICS: 'thong-ke',


    //chủ trọ
    HOST: '/chu-tro',
    ROOM_LIST: 'danh-sach-phong-tro',
    ADD_ROOM: 'them-phong-tro',
    EDIT_ROOM: 'sua-phong-tro/:id',
    ROOM_LIST_DETAIL: 'chi-tiet-phong-tro/:id',
    ROOM_LIST_DELETE: 'phong-tro-da-xoa',
    ALL_BOOKING: 'yeu-cau-dat-phong',
    ALL_BOOKED_ROOM: 'danh-sach-phong-da-dat',
    ALL_BOOKING_DETAIL: 'chi-tiet-dat-phong/:id',
    BOOKED_USER: 'danh-sach-nguoi-dat',
    BOOKED_USER_DETAIL: 'chi-tiet-nguoi-dat/:id',
    HOST_PROFILE: 'thong-tin-ca-nhan',
    CHANGE_PASSWORD_HOST: 'doi-mat-khau',
    REVENUE_STATISTIC: "thong-ke-doan-thu",

}